# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.warning.mode=all

# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.2
loader_version=0.19.3
# Mod Properties
mod_version=0.12.3
maven_group=me.marin
archives_base_name=lockout-fabric
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.157.0+26.2
